print()
print("Unpacking tuples with different data types")
int_val = int(input("Введить будь ласка ціле число: "))
flo_val = float(input("Введить будь ласка дробне число: "))
str_val = input("Введить будь ласка текстове значення: ")
boo_val = input("Введить будь ласка або 'True' або 'False': ").strip().lower() == "true"
data = (int_val, flo_val, str_val, boo_val)
print()
print(f"data = {data}")
print()
print(f"Data (Type: {type(data)})")
print()
print(f"Integer: {data[0]} (Type: {type(data[0])})") 
print(f"Float: 3.14 {data[1]} (Type: {type(data[1])})")
print(f"String: {data[2]} (Type: {type(data[2])})")
print(f"Boolean: {data[3]} (Type: {type(data[3])})")